server:
  port: 5000
database:
  type: postgres
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: security_db
minio:
  endpoint: localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: securitymuaraenim
  region: us-east-1
  useSSL: false
openai:
  apiKey: ""
  model: gpt-4.1-mini

